#!/bin/bash
echo "OCP console URL:"
echo "https://$(oc get routes --all-namespaces|grep console|grep -v downloads|awk '{print $3}')"
echo "----------"
echo "MTA / Tackle console URL: "
echo $(oc get routes --all-namespaces|egrep 'tackle-ui|mta-ui'|awk '{print "https://"$3}')
