#!/bin/bash
export cluster=$1
export KUBECONFIG=~/cnv-qe.rhcloud.com/$cluster/auth/kubeconfig
oc login -u kubeadmin -p $(cat ~/cnv-qe.rhcloud.com/$cluster/auth/kubeadmin-password) -n default
export cypress_user='admin'
export cypress_pass='Dog8code'
export cypress_tackleUrl=$(oc get routes --all-namespaces|egrep 'tackle-ui|mta-ui'|awk '{print "https://"$3}')
export cypress_keycloakAdminPassword=$(oc get secret credential-mta-rhsso -nopenshift-mta -o json |grep -i password|cut -d "\"" -f 4|base64 -d;)
export cypress_git_user=""
export cypress_git_password=""
export cypress_rwx_enabled="true"
cd ~/github.com/tackle-ui-tests
npx cypress open

