#!/bin/bash
export KUBECONFIG=~/.kube/config
export cypress_user='admin'
export cypress_pass='Dog8code'
export cypress_tackleUrl="http://"$(minikube ip)
echo $cypress_tackleUrl

export cypress_keycloakAdminPassword=$(oc get secret tackle-keycloak-sso -nkonveyor-tackle -o json|grep password|cut -d "\"" -f 4 |base64 -d; echo)

export cypress_rwx_enabled="true"
export cypress_git_user="ibragins"
export cypress_git_password=$(cat ~/.secrets/git_password)
export cypress_jira_atlassian_cloud_url="https://ibragins.atlassian.net/"
export cypress_jira_atlassian_cloud_email="ibragins@redhat.com"
export cypress_jira_atlassian_cloud_token=$(cat ~/.secrets/jira_cloud_token)
export cypress_jira_stage_datacenter_url="https://issues.stage.redhat.com"
export cypress_jira_stage_bearer_token=$(cat ~/.secrets/jira_stage_token)
export cypress_jira_atlassian_cloud_project="mta_integration"
export cypress_jira_stage_basic_login="mta-qe"
export cypress_jira_stage_basic_password=$(cat ~/.secrets/jira_stage_password)


export cypress_rwx_enabled="true"
export cypress_logLevel="VERBOSE"
cd ~/github.com/tackle-ui-tests
npx cypress open
