#!/bin/bash
export cluster=$1
export KUBECONFIG=~/cnv-qe.rhcloud.com/$cluster/auth/kubeconfig
oc login -u kubeadmin -p $(cat ~/cnv-qe.rhcloud.com/$cluster/auth/kubeadmin-password) -n default
export cypress_user='admin'
export cypress_pass='Dog8code'
export cypress_tackleUrl=$(oc get routes --all-namespaces|egrep 'tackle-ui|mta-ui'|awk '{print "https://"$3}')
export cypress_keycloakAdminPassword=$(oc get secret tackle-keycloak-sso -nkonveyor-tackle -o json|grep password|cut -d "\"" -f 4 |base64 -d; echo)
# export cypress_mavenXml=$(cat ~/github.com/tackle-ui-tests/cypress/fixtures/xml/settings.txt)
export cypress_git_user="ibragins"
export cypress_git_password="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"
cd ~/github.com/tackle-ui-tests
npx cypress open

